on: 
  workflow_dispatch:
  schedule:
    - cron: '*/375 * * * *'
jobs:
  rclone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: rclone
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      with:
        args: copy mov:/mov dm:/mov --ignore-existing -u -P --stats-one-line --transfers=10 --ignore-errors --buffer-size=200M --check-first --checkers=20
